### PR TITLE
encoding: Fix InterestPacketValue class

### PR DESCRIPTION
**Pull request by tuple71**
The InterestSignatureInfo element SHOULD include
at least one of the following elements:
SignatureNonce, SignatureTime, SignatureSeqNum.

### CODE REVIEW

**Comment by Pesa** [comment]
SHOULD != MUST, the choice of which signed Interest elements are included should be left up to the application (it's an app-level protocol decision). That's how we're implementing it in ndn-cxx, https://gerrit.named-data.net/c/ndn-cxx/+/6221

**Comment by tuple71** [comment]
Currently, in the ndn-cxx/security/validation-policy-command-interest.cpp, ValidationPolicyCommandInterest::parseCommandInterest() is checked timestamp in case of SignedInterestFormat::V03.

**Comment by tuple71** [comment]
I checked your implementation(https://gerrit.named-data.net/c/ndn-cxx/+/6221)

**Comment by Pesa** [comment]
Command interest is NOT equivalent to signed interest. Command interest is a special subcategory/extension of signed interest with more specific rules and is mostly a remnant of the old signed interest format.

**Comment by tuple71** [comment]
I know. Signed interest is being implemented now and is not currently released on ndn-cxx master branch.
When will it be released?

**Comment by zjkmxy** [comment]
Thank you for bringing this question up. These fields should be written by the signer, but I haven't written this part yet. Currently there is no stable application that is making use of these, so I don't know which one is better.

**Comment by Pesa** [comment]
> I know. Signed interest is being implemented now and is not currently released on ndn-cxx master branch.
> When will it be released?

ndn-cxx-0.7.1 has a complete implementation of the v0.3 Signed Interest format.

**Pull request closed without merging**
